### ISSUE TITLE
Too many issues to list.....

### ISSUE THREAD

**Issue by Buddyboy-git** [redbastie/larawire#2]
Ran composer command.  Barely any dependencies passed the version requirements.

C:\xampp\htdocs\ordergenie>composer require redbastie/larawire
Using version ^1.2 for redbastie/larawire
./composer.json has been updated
Running composer update redbastie/larawire --with-all-dependencies
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - torann/geoip[dev-master, 1.2.0, ..., 1.2.1] require php ^7.2 -> your php version (8.0.0) does not satisfy that requirement.
    - torann/geoip[1.0.10, ..., 1.1.x-dev] require php ^7.1 -> your php version (8.0.0) does not satisfy that requirement.
    - torann/geoip 1.0.9 requires php ^7.0 -> your php version (8.0.0) does not satisfy that requirement.
    - illuminate/support[v5.6.0, ..., 5.8.x-dev] require php ^7.1.3 -> your php version (8.0.0) does not satisfy that requirement.
    - jamesmills/laravel-timezone[1.9.0, ..., 1.9.2] require laravel/framework 5.6.* || 5.7.* || 5.8.* || ^6 || ^7 -> found laravel/framework[v5.6.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev] but it conflicts with your root composer.json require (^8.12).
    - Root composer.json requires redbastie/larawire ^1.2 -> satisfiable by redbastie/larawire[1.2.0].
    - Conclusion: don't install laravel/framework v8.12.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.12.2 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.12.3 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.13.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.14.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.15.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.16.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.16.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.17.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.17.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.17.2 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.18.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.18.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.19.0 (conflict analysis result)
    - redbastie/larawire 1.2.0 requires jamesmills/laravel-timezone ^1.9 -> satisfiable by jamesmills/laravel-timezone[1.9.0, 1.9.1, 1.9.2, 1.9.3].
    - torann/geoip 1.0.x-dev is an alias of torann/geoip dev-master and thus requires it to be installed too.
    - jamesmills/laravel-timezone 1.9.3 requires torann/geoip ^1.0 -> satisfiable by torann/geoip[1.0.0, ..., 1.2.1].
    - torann/geoip[1.0.0, ..., 1.0.x-dev] require illuminate/support ~5.0 -> satisfiable by illuminate/support[v5.0.0, ..., 5.8.x-dev].
    - torann/geoip 1.0.8 requires illuminate/support 5.0.* || 5.1.* || 5.2.* || 5.3.* || 5.4.* || 5.5.* || 5.6.* || 5.7.* -> satisfiable by illuminate/support[v5.0.0, ..., 5.7.x-dev].
    - torann/geoip[1.0.6, ..., 1.0.7] require illuminate/support 5.0.* || 5.1.* || 5.2.* || 5.3.* || 5.4.* || 5.5.* || 5.6.* -> satisfiable by illuminate/support[v5.0.0, ..., 5.6.x-dev].
    - Only one of these can be installed: illuminate/support[v5.0.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev], laravel/framework[v8.12.0, ..., 8.x-dev]. laravel/framework replaces illuminate/support and thus cannot coexist with it.
    - redbastie/larawire 1.2.0 requires laravel/framework ^8.0 -> satisfiable by laravel/framework[v8.12.0, ..., 8.x-dev].
    - Conclusion: don't install laravel/framework v8.12.0 (conflict analysis result)

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by redbastie** [comment]
It looks like you're using PHP 8, and some of the packages required by Larawire do not support PHP 8 yet.
