### ISSUE TITLE
Feature Request - Tailwind & Php artisan html

### ISSUE THREAD

**Issue by uarefans** [redbastie/larawire#5]
Hello, 

Im enjoy using your composer,

i think would be great to using tailwind than bootstrap, just my opinion, i starts edit to tailwind and make each input or datatables to component, and finally a little remake fot stubs, so can reuse more easy

and in closed issues i watch conversations about

1. Update model
2. php artisan html
3. Then livewire view and controller update file get data from model

Any eta for this request? i think would be great
Thank you

**Comment by redbastie** [comment]
My new package uses tailwind: https://github.com/redbastie/tailwire
